[build]
  functions = "functions"

[[redirects]]
  from = "/"
  to = "https://fayln.com"
  status = 301

[[redirects]]
  from = "/:name"
  to = "/.netlify/functions/redirect/:name"
  status = 200

[[redirects]]
  from = "/:name/:path"
  to = "/.netlify/functions/redirect/:name/:path"
  status = 200

